version: "3.8"

services:
  db:
    image: postgres:13.2
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
  api:
    command: ["python3", "-u", "-m", "auction.api"]
    image: luissaybe/auction
    environment:
      - DB_URL=postgres://postgres:postgres@db:5432/postgres
    volumes:
      - ./:/root/project
    ports:
      - "9000:9000"
    depends_on:
      - db
  cron_certify_item:
    command: ["python3", "-u", "-m", "auction.cron.certify_item"]
    image: luissaybe/auction
    environment:
      - DB_URL=postgres://postgres:postgres@db:5432/postgres
    volumes:
      - ./:/root/project
    depends_on:
      - db
