version: "3.8"

services:
  db:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  api:
    image: luissaybe/auction
    command: ["python3", "-u", "-m", "auction"]
    environment:
      - DB_URL=postgres://postgres:postgres@db:5432/postgres
    volumes:
      - ./:/tmp/project
    ports:
      - "9000:9000"
