version: "3.8"

services:
  db:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  api:
    image: luissaybe/auction
    command: ["python3", "-u", "-m", "auction"]
    volumes:
      - ./:/tmp/project
    ports:
      - "9000:9000"
