version: "3.8"

services:
  api:
    command: ["python3", "-um", "auction.api"]
    image: luissaybe/auction
    environment:
      - DB_URL=mongodb://db1:27017
    volumes:
      - ./:/root/project
    ports:
      - "9000:9000"
    depends_on:
      - db1
  db1:
    image: mongo:5.0.3
  cron_certify_item:
    command: ["python3", "-um", "auction.cron.certify_item"]
    image: luissaybe/auction
    environment:
      - DB_URL=mongodb://db1:27017
    volumes:
      - ./:/root/project
    depends_on:
      - db1
