apiVersion: v1
kind: Service
metadata:
  name: api-external-service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-size-slug: "lb-small"
spec:
  selector:
    app: auction-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
