name: builder master
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: dockerhub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build and push docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: luissaybe/auction:latest
